sudo: required
dist: trusty
branches:
  only:
    - master
    - dev
language: python
cache:
    - pip
    - directories:
        - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/
        - /home/travis/virtualenv/python2.7.9/bin/
        - capstone
        - unicorn
install:
  - sudo apt-get -y install gdb
  - lsb_release -a
  - pip install -r requirements.txt
  - sudo ./setup.sh
script:
  - futurize --all-imports --stage1 --print-function --write --unicode-literals pwndbg
  - git diff-index --quiet HEAD -- pwndbg
  - isort --check-only --diff --recursive pwndbg
  - nosetests ./tests/
  - python2.7 -m py_compile ida_script.py $(git ls-files 'pwndbg/*.py')
  - python3   -m py_compile               $(git ls-files 'pwndbg/*.py')
