version: "3.8"
services:
  base: &base-spec
    build: .
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
  main:
    <<: *base-spec
    volumes:
      - .:/pwndbg

  ubuntu22.04:
    <<: *base-spec
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: ubuntu:22.04
  
  ubuntu24.04:
    <<: *base-spec
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: ubuntu:24.04


  debian11:
    <<: *base-spec
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: debian:11

  lldb:
    <<: *base-spec
    build:
      context: .
      dockerfile: Dockerfile.lldb
      args:
        image: debian:12
    volumes:
      - .:/pwndbg

  archlinux:
    <<: *base-spec
    build:
      context: .
      dockerfile: Dockerfile.arch
      args:
        image: archlinux:latest
