name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Cache for pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ matrix.os }}-cache-pip

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install linters
      run: |
        pip install isort
        pip install black
        pip install flake8
        sudo snap install shfmt

    - name: Run linters
      run: |
        git diff-index --quiet HEAD -- pwndbg tests
        ./lint.sh
